### ISSUE TITLE
Removed nodes with duplicate peerIds from the peerlist

### ISSUE THREAD

**Issue by oed** [ceramicnetwork/peerlist#55]
Two nodes in the peerlist shared the same PeerId (which means that these two nodes share the same private key). We suspect this has caused some issues we have observed on nodes 3Box Labs are hosting on mainnet. These two nodes were removed from the peerlist for now.
```
"/dns4/ipfs-ceramic-elp-external.ownershiplabs.com/tcp/4012/ws/p2p/QmSiSc4WetTWsNzv8ukpXk57tyDNVqwbvMAKp1MUvo5pF8",
"/dns4/ipfs-ceramic-elp.yam.finance/tcp/4012/ws/p2p/QmSiSc4WetTWsNzv8ukpXk57tyDNVqwbvMAKp1MUvo5pF8",
```

- [ ] #23

- [ ] #29

@lyd0 @ethedev Maybe you can provide some additional context as to how this happened? Also if you want to add back your nodes please submit a new PR with updated PeerIds for your nodes!

**Comment by lyd0** [comment]
Hello, I resubmitted the pr, please take care of it [https://github.com/ceramicnetwork/peerlist/pull/56](url)

**Comment by lyd0** [comment]
> Two nodes in the peerlist shared the same PeerId (which means that these two nodes share the same private key). We suspect this has caused some issues we have observed on nodes 3Box Labs are hosting on mainnet. These two nodes were removed from the peerlist for now.
> 
> ```
> "/dns4/ipfs-ceramic-elp-external.ownershiplabs.com/tcp/4012/ws/p2p/QmSiSc4WetTWsNzv8ukpXk57tyDNVqwbvMAKp1MUvo5pF8",
> "/dns4/ipfs-ceramic-elp.yam.finance/tcp/4012/ws/p2p/QmSiSc4WetTWsNzv8ukpXk57tyDNVqwbvMAKp1MUvo5pF8",
> ```
> 
> * [ ]  [Add Dataverse node to MainNet #23](https://github.com/ceramicnetwork/peerlist/pull/23)
> * [ ]  [Yam Ceramic Node #29](https://github.com/ceramicnetwork/peerlist/pull/29)
> 
> @lyd0 @ethedev Maybe you can provide some additional context as to how this happened? Also if you want to add back your nodes please submit a new PR with updated PeerIds for your nodes!

Hello, I resubmitted the pr, please take care of it [https://github.com/ceramicnetwork/peerlist/pull/56](url)
